# Generated by Django 4.2 on 2025-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_visitorip_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
