name: Deploy Django to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-django-app-123'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Set Azure App Settings
        run: |
          az webapp config appsettings set \
            --name my-django-app-123 \
            --resource-group my-django-app \
            --settings \
              CWA_API_KEY=${{ secrets.CWA_API_KEY }} \
              OTHER_SETTING=value